config/routes.rb
Rails.application.routes.draw do
  root to: "homes#index", via: :get
  resources :users, only: [:show, :edit, :update]
  resources :events, only: [:new, :create, :show]
  resource :calendar, only: [:show]
  resource :session, only: [:destroy]
  resource :feedback, only: [:new, :create]
  get "/auth/:provider/callback", to: "sessions#create"
  get "/tutors", to: "users#tutor"
end

app/models/authorization.rb
require "net/http"
require "json"

class Authorization < ActiveRecord::Base
  belongs_to :user

  validates_presence_of :user_id, :uid, :provider, :token, :refresh_token,
    :expires_at
  validates_uniqueness_of :uid, :token, :refresh_token, :expires_at,
    scope: :provider

  def self.find_from_hash(hash)
    find_by_provider_and_uid(hash[:provider], hash[:uid])
  end

  def self.create_from_hash(hash, user = nil)
    user ||= User.create_from_hash!(hash)

    Authorization.create(user: user, uid: hash[:uid], provider: hash[:provider],
                         token: hash[:credentials][:token],
                         refresh_token: hash[:credentials][:refresh_token],
                         expires_at: Time.at(
                           hash[:credentials][:expires_at]).to_datetime
                        )
  end

  def request_token_from_google
    Net::HTTP.post_form(url, google_to_params)
  end

  def refresh!
    response = request_token_from_google
    data = JSON.parse(response.body)
    update_attributes(
      token: data["access_token"],
      expires_at: Time.now + data["expires_at"].to_i.seconds
    )
  end

  def expired?
    expires_at < Time.now
  end

  def fresh_token
    refresh! if expired?
    token
  end

  private

  def google_to_params
    {
      "refresh_token" => refresh_token,
      "client_id" => "994748866932-7kjt7fhipagmcnu65i1otnl4fmvhdp9s" \
      ".apps.googleusercontent.com",
      "client_secret" => "VhbOQPFuYJGIEzZ5dsbGFzD2",
      "grant_type" => "refresh_token"
    }
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_and_belongs_to_many :users

  validates_presence_of :name, :event_date, :users
end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
  belongs_to :user

  validates_presence_of :rating, :user_id
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  has_and_belongs_to_many :tutors
end

app/models/tutor.rb
class Tutor < ActiveRecord::Base
  belongs_to :user
  validates :user_id, presence: true, uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :feedbacks
  has_many :authorizations
  has_and_belongs_to_many :events

  validates :email, presence: true, uniqueness: true
  validates :name, presence: true, uniqueness: true

  def self.find_from_hash(hash)
    find_by_name(hash[:info][:name])
  end

  def self.create_from_hash!(hash)
    create(name: hash[:info][:name], email: hash[:info][:email],
           image_url: hash[:info][:image])
  end

  def self.find_tutor(search)
    if search
      where(is_tutor: true, name: search)
    else
      where(is_tutor: true)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

  def signed_in?
    !!current_user
  end

  helper_method :current_user, :signed_in?

  def current_user=(user)
    @current_user = user
    session[:user_id] = user.id
  end
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
  def show
    @tutor = User.find(session[:calendar_for_id])
    @user = current_user
    @events = @user.events.group_by(&:event_date)
    @date = params[:date] ? Date.parse(params[:date]) : Date.today
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def new
    @event = Event.new
    @tutor = User.find(session[:event_for_id])
    @student = current_user
  end

  def show
    @event = Event.find(params[:id])
  end

  def create
    @users = [User.find(event_params[:student_id]), User.find(event_params[:tutor_id])]
    @event_details = {
      name: event_params[:name],
      location: event_params[:location],
      event_date: event_params[:event_date],
      event_time: event_params[:event_time],
      users: @users
    }

    @event = Event.new(@event_details)

    if @event.save
      flash[:notice] = "Successfully added event"
      redirect_to user_path(current_user)
    else
      flash[:alert] = "Something went wrong :("
      redirect_to user_path(event_params[:tutor_id])
    end
  end

  private

  def event_params
    params.require(:event).permit(:name, :location, :event_date, :event_time,
                                  :student_id, :tutor_id)
  end
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  def new
    @feedback = Feedback.new
    @user = User.find(session[:feedback_for_id])
  end

  def create
    @feedback = Feedback.new(feedback_params)

    if @feedback.save
      flash[:notice] = "Successfully added feedback"
      redirect_to user_path(feedback_params[:user_id])
    else
      flash[:alert] = "Something went wrong :("
      redirect_to user_path(feedback_params[:user_id])
    end
  end

  private

  def feedback_params
    params.require(:feedback).permit(:rating, :comment, :user_id)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end

  def setup
    @user = current_user
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    unless @auth = Authorization.find_from_hash(auth_hash)
      @auth = Authorization.create_from_hash(
        auth_hash, User.find_from_hash(auth_hash)
      )
    end

    self.current_user = @auth.user

    flash[:notice] = "Successfully Signed In As #{current_user.name}"
    redirect_to edit_user_path(current_user)
  end

  def destroy
    session[:user_id] = nil

    flash[:notice] = "Successfully Signed Out"
    redirect_to root_path
  end

  private

  def auth_hash
    request.env["omniauth.auth"]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def tutor
    @tutors = User.find_tutor(params[:search])
  end

  def edit
    if current_user.is_tutor.nil?
      @user = current_user
    else
      redirect_to user_path(current_user)
    end
  end

  def show
    @user = User.find(params[:id])
    session[:feedback_for_id] = @user.id
    session[:calendar_for_id] = @user.id
    session[:event_for_id] = @user.id
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(is_tutor: params[:is_tutor])
      flash[:notice] = "Successfully saved changes, welcome #{current_user.name}"
      redirect_to user_path(current_user)
    else
      flash[:alert] = "Something went wrong :("
      render "edit"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar_url(user)
    if user.image_url.present?
      user.image_url
    else
      "default.png"
    end
  end
end

app/helpers/calendar_helper.rb
module CalendarHelper
  def calendar(date = Date.today, &block)
    Calendar.new(self, date, block).table
  end

  class Calendar < Struct.new(:view, :date, :callback)
    HEADER = %w(Sunday Monday Tuesday Wednesday Thursday Friday Saturday)
    START_DAY = :sunday

    delegate :content_tag, to: :view

    def table
      content_tag :table, class: "calendar table table-bordered table-stripped" do
        header + week_rows
      end
    end

    def header
      content_tag :tr do
        HEADER.map { |day| content_tag :th, day }.join.html_safe
      end
    end

    def week_rows
      weeks.map do |week|
        content_tag :tr do
          week.map { |day| day_cell(day) }.join.html_safe
        end
      end.join.html_safe
    end

    def day_cell(day)
      content_tag :td, view.capture(day, &callback), class: day_classes(day)
    end

    def day_classes(day)
      classes = []
      classes << "today" if day == Date.today
      classes << "not-month" unless day.month == date.month
      classes.empty? ? nil : classes.join(" ")
    end

    def weeks
      first = date.beginning_of_month.beginning_of_week(START_DAY)
      last = date.end_of_month.end_of_week(START_DAY)
      (first..last).to_a.in_groups_of(7)
    end
  end
end

app/views/calendars/show.html.erb
<div class="row">
  <div class="col-md-12 text-center">
    <div class="well controls">
      <%= link_to calendar_path(date: @date - 1.month), class: "btn btn-default" do %>
        <i class="glyphicon glyphicon-backward"></i>
      <% end %>
      <%= "#{@date.strftime("%B")} #{@date.year}" %>
      <%= link_to calendar_path(date: @date + 1.month), class: "btn btn-default" do %>
        <i class="glyphicon glyphicon-forward"></i>
      <% end %>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <%= calendar @date do |date| %>
      <%= date.day %>
      <% if @events[date] %>
        <ul>
          <% @events[date].each do |event| %>
            <li><%= link_to event.name, event %></li>
          <% end %>
        </ul>
      <% end %>
    <% end %>
  </div>
</div>

app/views/events/new.html.erb
<h1>Create a new event</h1>

<%= form_for @event, url: {action: :create} do |f| %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, value: "Session #{@student.name}-#{@tutor.name}", class: "form-control"%>
  </div>

  <div class="form-group">
    <%= f.label :location %>
    <%= f.text_field :location, class: "form-control"%>
  </div>

  <div class="form-group">
    <%= f.label :event_date %>
    <%= f.date_field :event_date, value: Date.today, class: "form-control"%>
  </div>

  <div class="form-group">
    <%= f.label :event_time %>
    <%= f.time_field :event_time, class: "form-control"%>
  </div>

  <div class="form-group">
    <%= f.label :student %>
    <%= f.text_field :student, value: @student.name, class: "form-control"%>
  </div>

  <div class="form-group">
    <%= f.label :tutor %>
    <%= f.text_field :tutor, value: @tutor.name, class: "form-control"%>
  </div>

  <div class="form-group hidden">
    <%= f.label :student_id %>
    <%= f.number_field :student_id, value: @student.id, class: "form-control"%>
  </div>

  <div class="form-group hidden">
    <%= f.label :tutor_id %>
    <%= f.number_field :tutor_id, value: @tutor.id, class: "form-control"%>
  </div>

  <%= f.submit "Create Event", class: "btn btn-primary" %>
<% end %>

app/views/events/show.html.erb
<h1><%= @event.name %></h1>
<h3>Location: <%= @event.location %></h3>
<h3>Date: <%= @event.event_date %></h3>
<h3>Time: <%= @event.event_time %></h3>
<h3>
  Attending:
  <ul>
    <% @event.users.each do |user| %>
      <li><%= user.name %></li>
    <% end %>
  </ul>
</h3>

app/views/feedbacks/new.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success"><%= flash[:notice] %></div>
<% end %>

<% if flash[:alert] %>
  <div class="alert alert-danger"><%= flash[:alert] %></div>
<% end %>

<h1>Leave a feedback!</h1>
<%= form_for @feedback, url: {action: :create} do |f| %>
  <div class="form-group">
    <%= f.label :rating %>
    <%= f.number_field(:rating, in: 1.0..5.0, step: 0.5, class: "form-control") %>
  </div>

  <div class="form-group">
    <%= f.label :comment %>
    <%= f.text_area :comment, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :user_name, "Feedback For" %>
    <%= f.text_field :user_name, value: @user.name, class: "form-control" %>
  </div>

  <div class="form-group hidden">
    <%= f.number_field :user_id, value: @user.id %>
  </div>

  <%= f.submit "Submit Feedback", class: "btn btn-primary" %>
<% end %>

app/views/homes/index.html.erb
<% if flash[:notice] %>
  <div class="alert alert-info"><%= flash[:notice] %></div>
<% end %>

<div class="jumbotron">
  <h1>Welcome to Tutorify!</h1>
  <p>Where Students Meet Tutors.</p>

  <% unless signed_in? %>
    <div class="row">
      <div class="col-md-offset-3 col-md-3">
        <%= link_to("Sign in with Facebook", "auth/facebook") %>
      </div>
      <div class="col-md-3">
        <%= link_to("Sign in with Google", "auth/google_oauth2") %>
      </div>
    </div>
  <% end %>
</div>

app/views/homes/setup.html.erb
<%= form_for @user do |form| %>

  <div class="form-group">
    <p>Please identify if you are a Student or a Tutor:</p>
    <%= radio_button_tag(:is_tutor, true) %>
    <%= label_tag(:user_tutor, "I am a Tutor") %>
    <br>
    <%= radio_button_tag(:is_tutor, false) %>
    <%= label_tag(:user_student, "I am a Student") %>
  </div>

  <div class="form-group">
    <%= form.submit("Submit", class: "btn btn-primary") %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tutorify</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <% if current_user %>
            <%= link_to "Tutorify", user_path(current_user), class: "navbar-brand" %>
          <% else %>
            <%= link_to "Tutorify", root_path, class: "navbar-brand" %>
          <% end %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <% if signed_in? %>
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
              <% unless current_user.is_tutor %>
                <li>
                  <%= link_to "Find a Tutor", tutors_path %>
                </li>
              <% end %>
              <li>
                <%= link_to "My Calendar", calendar_path %>
              </li>
              <li>
                <%= link_to("Sign Out", session_path, method: :delete, class: 'pull-right') %>
              </li>
          </div><!-- /.navbar-collapse -->
        <% end %>
      </div><!-- /.container-fluid -->
    </nav>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/edit.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success"><%= flash[:notice] %></div>
<% end %>

<% if flash[:alert] %>
  <div class="alert alert-danger"><%= flash[:alert] %></div>
<% end %>

<h1>Are you a Student or a Tutor?</h1>

<%= form_for @user do |f| %>
  <div class="form-group">
    <%= radio_button_tag :is_tutor, "false", class: "form-control" %>
    <%= label_tag(:is_tutor, "I am a Student") %>
  </div>

  <div class="form-group">
    <%= radio_button_tag :is_tutor, "true", class: "form-control" %>
    <%= label_tag(:is_tutor, "I am a Tutor") %>
  </div>

  <%= f.submit "Save", class: "btn btn-primary" %>
<% end %>

app/views/users/show.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success"><%= flash[:notice] %></div>
<% end %>

<% if flash[:alert] %>
  <div class="alert alert-warning"><%= flash[:alert] %></div>
<% end %>


<div class="row">
  <div class="col-md-4">
    <%= image_tag(avatar_url(@user), width: "200", height: "200", class: "img-circle pull-right") %>
  </div>
  <div class="col-md-4 user-info">
    <p class="user-name"><%= @user.name %></p>
    <p class="user-status">
      <% if @user.is_tutor %>
        <p>Tutor</p>
      <% else %>
        <p>Student</p>
      <% end %>
    </p>
  </div>

  <% unless @user == current_user %>
    <div class="col-md-4 feedback">
      <%= link_to "Leave a Feedback", new_feedback_path %>
      <% if @user.is_tutor && current_user.is_tutor != true %>
        <%= link_to "Book a session", new_event_path %>
      <% end %>
    </div>
  <% end %>
</div>

<% if @user.feedbacks.present? %>
  <div class="row feedback-list">
    <% @user.feedbacks.limit(5).sort_by(&:created_at).reverse!.each do |feedback| %>
      <div class="row feedback-row">
        <div class="col-md-2">
          <p>Rating: <%= feedback.rating %></p>
        </div>

        <div class="col-md-8">
          <p>Comment: <%= feedback.comment %></p>
        </div>

        <div class="col-md-2">
          <p>Created At: <%= feedback.created_at.to_formatted_s(:short) %></p>
        </div>
      </div>
    <% end %>
  </div>
<% else %>
  <p class="text-center">No Feedbacks yet!</p>
<% end %>

app/views/users/tutor.html.erb
<h1>Find a Tutor</h1>

<%= form_tag tutors_path, method: :get do %>
  <div class="form-group">
    <%= text_field_tag :search, params[:search], class: "form-control" %>
    <%= submit_tag "Search", name: nil, class: "btn btn-primary form-control" %>
  </div>
<% end %>

<div class="row">
  <div class="col-md-offset-3 col-md-6">
    <ul class="tutor-list">
      <% @tutors.each do |tutor| %>
        <li><%= link_to tutor.name, user_path(tutor) %></li>
      <% end %>
    </ul>
  </div>
</div>